### PR TITLE
Added consumer to output

### PR DESCRIPTION
**Pull request by jgraham0325**

### CODE REVIEW

**Comment by jgraham0325** [comment]
Couldn't run integration tests locally (colleague had same problem) so creating a pull request to get Travis to run them...

**Comment by justin-r-oliver** [comment]
Changelog needs updating

**Comment by justin-r-oliver** [comment]
Raised JIRA ticket TP-973

**Comment by matt-rich** [comment]
Completed by pull request in 3.2.0.

**Pull request closed without merging**
